package com.turbo_extreme_sloth.ezzence.activities;

import org.json.JSONException;
import org.json.JSONObject;

import android.app.AlertDialog;
import android.app.ProgressDialog;
import android.content.Intent;
import android.os.Bundle;
import android.widget.LinearLayout;
import android.widget.TableLayout;
import android.widget.Toast;

import com.turbo_extreme_sloth.ezzence.CurrentUser;
import com.turbo_extreme_sloth.ezzence.R;
import com.turbo_extreme_sloth.ezzence.SharedPreferencesHelper;
import com.turbo_extreme_sloth.ezzence.config.Config;
import com.turbo_extreme_sloth.ezzence.rest.RESTRequest;
import com.turbo_extreme_sloth.ezzence.rest.RESTRequestEvent;
import com.turbo_extreme_sloth.ezzence.rest.RESTRequestListener;

public class ConsumptionOverviewActivity extends BaseActivity implements RESTRequestListener
{
	/** Elements */
	protected LinearLayout tabsLinearLayout;
	
	protected TableLayout dataTableLayout;
	
	protected ProgressDialog progressDialog;
	
	@Override
	protected void onCreate(Bundle savedInstanceState)
	{
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_consumption_overview);
		
		tabsLinearLayout = (LinearLayout) findViewById(R.id.activity_consumption_overview_tabs);
		
		dataTableLayout = (TableLayout) findViewById(R.id.activity_consumption_overview_data);
		
		// Load data from server
		RESTRequest restRequest = new RESTRequest(Config.REST_REQUEST_BASE_URL + Config.REST_REQUEST_USAGE_STATS);
		
		restRequest.putString("sessionID", CurrentUser.getCurrentUser().getSessionID());
		
		restRequest.addEventListener(this);
		
		restRequest.execute();
	}

	@Override
	public void RESTRequestOnPreExecute(RESTRequestEvent event)
	{
		progressDialog = new ProgressDialog(this);
		progressDialog.setTitle(getResources().getString(R.string.loading));
		progressDialog.show();
	}

	@Override
	public void RESTRequestOnPostExecute(RESTRequestEvent event)
	{
		progressDialog.dismiss();
		
		String result = event.getResult();
		
		// Check if the returned string isn't an error generated by the REST class
		if (RESTRequest.isExceptionCode(result))
		{
			Toast.makeText(this, getString(R.string.error_unknown_exception), Toast.LENGTH_SHORT).show();
			
			finish();
			
			return;
		}
		
		try
		{
			// Parse JSON
			JSONObject jsonObject = new JSONObject(result);
			
			
		}
		catch (JSONException e) { }
		
//		// Correct login, start main activity
//		if (user.isLoggedIn())
//		{
//			SharedPreferencesHelper.storeUser(this, user);
//			
//			CurrentUser.setCurrentUser(user);
//			
//			startActivity(new Intent(this, MainActivity.class));
//			
//			finish();
//		}
//		else
//		{
//			String message = event.getMessageFromResult();
//			
//			// The server couldn't be reached, as no message is set
//			if (message == null)
//			{
//				Toast.makeText(getApplicationContext(), getResources().getString(R.string.rest_not_found), Toast.LENGTH_SHORT).show();
//			}
//			// The server did not accept the passed user credentials
//			else
//			{
//				AlertDialog.Builder builder = new AlertDialog.Builder(LoginActivity.this);
//
//				builder.setTitle(R.string.login_failed);
//				builder.setMessage(R.string.login_wrong_credentials);
//				builder.setPositiveButton(R.string.ok, null);			
//				builder.show();
//			}
//		}
	}
}
